
spring:
  datasource:
    name: user
    url: jdbc:mysql://localhost:3306/user?useSSL=false&&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
